excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Templates
  - iOSTests
  - iOSUITests



whitelist_rules:

- array_init
#- attributes
- block_based_kvo
- class_delegate_protocol
- closing_brace
#- closure_end_indentation
- closure_parameter_position
- closure_spacing
- colon
- comma
- compiler_protocol_init
- conditional_returns_on_newline #Maybe opt
- contains_over_first_not_nil
- control_statement
- cyclomatic_complexity
- discarded_notification_center_observer #Maybe delete
- discouraged_direct_init
#- discouraged_object_literal #Maybe delete
#- discouraged_optional_boolean #Maybe delete
#- discouraged_optional_collection #Not the best for constructors
- dynamic_inline
- empty_count
- empty_enum_arguments
- empty_parentheses_with_trailing_closure 
- empty_string
#- explicit_acl
- explicit_enum_raw_value #Maybe delete
- explicit_init
#- explicit_top_level_acl
#- explicit_type_interface
- extension_access_modifier #Maybe delete
- fallthrough
- fatal_error_message
#- file_header #Maybe delete
- file_length
- first_where
- for_where
- force_cast
- force_try
- force_unwrapping
- function_body_length
- function_parameter_count
- generic_type_name
#- identifier_name
- implicit_getter
- implicit_return
- implicitly_unwrapped_optional
- is_disjoint
- joined_default_parameter
- large_tuple
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_nsgeometry_functions
- let_var_whitespace
- line_length
- literal_expression_end_indentation
- lower_acl_than_parent
- mark
#- modifier_order
#- multiline_arguments Because of readable code
- multiline_parameters
#- multiple_closures_with_trailing_closure
- nesting 
- nimble_operator
#- no_extension_access_modifier
#- no_grouping_extension #Extensions in same file get warning
#- notification_center_detachment
- number_separator
#- object_literal
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
#- prefixed_toplevel_constant # Maybe delete
- private_action    Because of the binding
#- private_outlet
- private_over_fileprivate #Maybe delete
- private_unit_test
- prohibited_super_call
- protocol_property_accessors_order
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_optional_initialization
- redundant_set_access_control
- redundant_string_enum_value
- redundant_void_return
- required_enum_case
- return_arrow_whitespace
- shorthand_operator
- single_test_class
- sorted_first_last
- sorted_imports
- statement_position
#- strict_fileprivate
- superfluous_disable_command
- switch_case_alignment
- switch_case_on_newline
- syntactic_sugar
- todo
- trailing_comma
- trailing_newline
- trailing_semicolon
#- trailing_closure  Beacuse of the subscribe closures
- type_body_length
- type_name
- unavailable_function
- unneeded_break_in_switch
- unneeded_parentheses_in_closure_argument
#- untyped_error_in_catch
- unused_closure_parameter
- unused_enumerated
- unused_optional_binding
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- vertical_whitespace
- void_return
- weak_delegate
- xctfail_message
- yoda_condition
- custom_rules
- hard_coded_string
- no_hiding_in_strings

#metrics
type_name:
  min_length: 5
  max_length: 
    warning: 20
    error: 30

identifier_name:
  min_length: 2
  max_length:
    warning: 30
    error: 40
  validates_start_with_lowercase: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length: 25
function_parameter_count: 5
large_tuple: 5
line_length: 240
nesting: 1
type_body_length:
  - 300 
  - 400


custom_rules:
    weak_self_closure:
        name: "Use weak self in closures"
        message: "Use weak self when create a closure."
        regex: "\\{\\s*[^\\[]{0,50}\\s+\\bin\\b([a-zA-Z\\\\.\\(\\)\\[\\{\\}\\>\\/\\=]|\\s)+(self)[^!]"

        severity: error
    disable_uicolor:
        name: "Do not use UIColor"
        message: "Do not use UIColor. Use it only Colors file"
        regex: "UIColor"

        severity: error

#Idomatic
force_cast: error
force_try: error
force_unwrapping: error
explicit_init: error
generic_type_name: error
implicitly_unwrapped_optional: error
legacy_cggeometry_functions: error
legacy_constant: error
legacy_constructor: error
legacy_nsgeometry_functions: error
nimble_operator: error
redundant_optional_initialization: error
redundant_void_return: error
type_name: error
unneeded_break_in_switch: error

#Lint
overridden_super_call: error
private_action: error
unused_closure_parameter: error
yoda_condition: error

#Style
attributes: error
closure_parameter_position: error
colon: error
comma: error
control_statement: error
empty_parameters: error
multiline_parameters: error
#multiple_closures_with_trailing_closure: error Because of the UIView.animate
operator_usage_whitespace: error
protocol_property_accessors_order: error
return_arrow_whitespace: error
shorthand_operator: error
statement_position: error


#Performance
sorted_first_last: error


reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
